[package]
name = "ferrite-ipi"
version = "0.1.0"
edition = "2021"

[dependencies]
ferrite-agent = { path = "../ferrite-agent" }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }
ammonia = "3"
regex = "1"
sha2 = "0.10"
hex = "0.4"
