[package]
name = "ferrite-ipi"
version = "0.1.0"
edition = "2021"

[dependencies]
ferrite-agent = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
ammonia = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
aes-gcm = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
rusqlite = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true }
