[package]
name = "ferrite-ui"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
iced = { workspace = true }
iced_widget = { workspace = true }
ferrite-core = { workspace = true }
ferrite-audit-log = { workspace = true }
ferrite-servo = { workspace = true }
ferrite-agent = { workspace = true }
ferrite-ipi = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
urlencoding = { workspace = true }
url = { workspace = true }
