[package]
name = "ferrite-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { workspace = true }
iced_widget = { workspace = true }
ferrite-audit-log = { workspace = true }
ferrite-servo = { workspace = true }
ferrite-agent = { workspace = true }
ferrite-ipi = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
urlencoding = { workspace = true }
